# -*- coding: utf-8 -*-
"""CIE2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tg-Fu6QeIzEB0cioOx2T16OTLmNCNJgs
"""

import pandas as pd
data=pd.read_csv("/content/titanic.csv")
data

data.describe()

data.info()

data.head()

data.isnull().sum()

data.shape

data.duplicated()

data['Pclass'].unique()

import numpy as np
from scipy import stats
mean1=np.mean(data['Age'])
median1=np.median(data['Age'])
mode1=stats.mode(data['Age'],keepdims=True).mode[0]
mean2=np.mean(data['Fare'])
median2=np.median(data['Fare'])
mode2=stats.mode(data['Age'],keepdims=True).mode[0]
print ("central tendency")
print ("mean age:", mean1)
print ("median age:", median1)
print ("mode age:", mode1)
print ("mean fare:", mean2)
print ("median fare:", median2)
print ("mode fare:", mode2)

import matplotlib.pyplot as plt
import pandas as pd
filtered_data = data[(data['Survived'].isin([0, 1])) & (data['Pclass'].isin([1, 2, 3]))]
counts = filtered_data.groupby(['Survived', 'Pclass'])['Survived'].count().unstack()
counts.plot(kind='bar', color=['red', 'yellow','k'])
plt.xlabel('Survived (0 = No, 1 = Yes)')
plt.ylabel('Number of Passengers')
plt.title('Total Numbers of Survived and Not Survived by Class')
plt.legend(title='Pclass')
plt.show()

import pandas as pd
null_values=data.isnull().sum()
filled_data=data.fillna(data.mean(numeric_only=True))
null_values,filled_data.head(5)

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
titanic_Age= titanic_data['Age'].dropna()
z_score = np.abs(stats.zscore(titanic_Age))
threshold = 3
outliers_z_score = titanic_Age[z_score > threshold]
print("Outliers detected using Z-score method:")
print(outliers_z_score)
plt.figure(figsize=(5,5))
sns.boxplot(x=titanic_data['Age'])
plt.title('Boxplot of Age')
plt.show()